server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

# 数据库连接配置
database:
  default:
    link:   "mysql:root:1111111q@tcp(127.0.0.1:3306)/em_markting"
    debug:  true

