// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeRegimentUpdateStockLog is the golang structure of table evente_regiment_update_stock_log for DAO operations like Where/Data.
type EventeRegimentUpdateStockLog struct {
	g.Meta           `orm:"table:evente_regiment_update_stock_log, do:true"`
	Id               interface{} //
	OrgId            interface{} // 主办id
	UserId           interface{} // 主办id
	RegimentId       interface{} // 团id
	IncrementId      interface{} // 主订单id
	GroupIncrementId interface{} // 团订单id
	ProductId        interface{} // 产品id
	ProductSubId     interface{} // 二级id  例如场次id
	ProductRelId     interface{} // 三级id 例如票品 规格id
	StockId          interface{} // 库存id
	Money            interface{} // 实售价格
	UpdateNum        interface{} // 扣减数量
	IsRollback       interface{} // 是否回滚
	CreateDate       *gtime.Time // 创建时间
	UpdateDate       *gtime.Time // 修改时间
}
