// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeOrgPushConf is the golang structure of table evente_org_push_conf for DAO operations like Where/Data.
type EventeOrgPushConf struct {
	g.Meta        `orm:"table:evente_org_push_conf, do:true"`
	Id            interface{} //
	OrgId         interface{} // org_id
	MessageGroup  interface{} // 消息分组
	MessageType   interface{} // 消息推送场景
	WeixinPush    interface{} // 主办公众号开关 1开 0 关
	EWeixinPush   interface{} // 活动易公众号开关 1开 0 关
	WeixinAppPush interface{} // 小程序开关 1开 0 关
	SmsPush       interface{} // 开关 1开 0 关
	EmailPush     interface{} // 开关 1开 0 关
	CreateDate    *gtime.Time // 新增时间
	UpdateDate    *gtime.Time // 更新时间
	DeleteDate    *gtime.Time // 删除时间
}
