// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeECardAvoidAppointment is the golang structure of table evente_e_card_avoid_appointment for DAO operations like Where/Data.
type EventeECardAvoidAppointment struct {
	g.Meta              `orm:"table:evente_e_card_avoid_appointment, do:true"`
	Id                  interface{} // 自增id
	UserId              interface{} // C端用户id
	OrgId               interface{} // 主办id
	CardId              interface{} // E通卡id
	CardSaleId          interface{} // E通卡销售表id
	PicId               interface{} // 活动图片id
	EventeId            interface{} // 活动id
	EventeName          interface{} // 活动名称
	ScreeningsId        interface{} // 场次id
	ScreeningsName      interface{} // 场次名称
	ScreeningsStartDate *gtime.Time // 场次开始时间
	ScreeningsEndDate   *gtime.Time // 场次结束时间
	VerificationName    interface{} // 核销人-主办名称
	CreateDate          *gtime.Time // 创建时间
	UpdateDate          *gtime.Time // 修改时间
}
