// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeFreeShipping is the golang structure of table evente_free_shipping for DAO operations like Where/Data.
type EventeFreeShipping struct {
	g.Meta           `orm:"table:evente_free_shipping, do:true"`
	Id               interface{} //
	OrgId            interface{} // 主办ID
	Title            interface{} // 商品标题
	FreeShippingMode interface{} // 包邮方式(1.满额包邮  2.满件包邮)
	FreeShippingType interface{} // 包邮条件（1.按商品优惠前总价，计算包邮  2.按商品优惠后总价，计算包邮）
	StartDate        *gtime.Time // 开始时间
	EndDate          *gtime.Time // 结束时间
	Rule             interface{} // 包邮地区规则
	CoverImg         interface{} // 封面图ID
	ProductType      interface{} // 产品类型（event 演出活动,goods 商品类型）
	IsCurrency       interface{} // 是否夸商品优惠（1是 2.否）
	ProductList      interface{} // 产品ID集合
	Status           interface{} // 商品状态（1正常 2删除）
	CreateDate       *gtime.Time // 创建时间
	UpdateDate       *gtime.Time // 更新时间
}
