// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeCoupon is the golang structure of table evente_coupon for DAO operations like Where/Data.
type EventeCoupon struct {
	g.Meta             `orm:"table:evente_coupon, do:true"`
	Id                 interface{} //
	OrgId              interface{} // 主办id
	Name               interface{} // 优惠券名称
	CouponType         interface{} // 优惠券类型 1代金券 2:折扣券
	Price              interface{} // 优惠券面额
	DiscountPercent    interface{} // 折扣比例
	UseConditionSwitch interface{} // 是否限制使用条件 0不限制 1限制
	UseCondition       interface{} // 使用条件 订单金额满这个数才可使用
	Number             interface{} // 发行量
	EventApplyType     interface{} // 适用活动方式 1全部活动 2指定活动参与 3指定活动不参与
	GoodsApplyType     interface{} // 适用商品方式 1全部商品 2指定商品参与 3指定商品不参与
	FetchedNumber      interface{} // 已经领取的数量
	FetchTimeSwitch    interface{} // 是否限制领取时间 0不限制 1限制
	FetchTimeInfo      interface{} // 领取时间限制序列化 兼容前数据
	FetchLimit         interface{} // 每人领取限额
	FetchEntry         interface{} // 领取入口 逗号分隔 1详情页
	FetchMemberSwitch  interface{} // 是否限制领取人等级 0不限制 1限制
	FetchMemberLevel   interface{} // 等级限制 逗号分隔
	Status             interface{} // 1-正常，2-删除,3-手动关闭
	CreateDate         *gtime.Time // 新增时间
	UpdateDate         *gtime.Time // 更新时间
}
