// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeECardDelayLog is the golang structure of table evente_e_card_delay_log for DAO operations like Where/Data.
type EventeECardDelayLog struct {
	g.Meta     `orm:"table:evente_e_card_delay_log, do:true"`
	Id         interface{} // 自增id
	OrgId      interface{} // 主办id
	ChildId    interface{} // 子账号id
	CardId     interface{} // E通卡id
	UserId     interface{} // 用户id
	CardSaleId interface{} // 销售id
	OrgName    interface{} // 主办名称
	BeforeDate *gtime.Time // 延期之前时间
	ExpireDate *gtime.Time // 到期时间
	CreateDate *gtime.Time // 创建时间
}
