// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeECardAppointmentPriceRel is the golang structure of table evente_e_card_appointment_price_rel for DAO operations like Where/Data.
type EventeECardAppointmentPriceRel struct {
	g.Meta        `orm:"table:evente_e_card_appointment_price_rel, do:true"`
	Id            interface{} // 自增id
	IncrementId   interface{} // 主单号
	AppointmentId interface{} // 预约主表id
	OrgId         interface{} //
	UserId        interface{} //
	PriceId       interface{} // 票品
	PriceName     interface{} //
	Price         interface{} //
	SeatsAttr     interface{} // 座位信息(json 结构化数据)
	Number        interface{} // 票品数量
	CreateDate    *gtime.Time // (预约时间)创建时间
	UpdateDate    *gtime.Time // 修改时间
}
