// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeFreeShippingProductEvent is the golang structure of table evente_free_shipping_product_event for DAO operations like Where/Data.
type EventeFreeShippingProductEvent struct {
	g.Meta         `orm:"table:evente_free_shipping_product_event, do:true"`
	Id             interface{} //
	OrgId          interface{} // 主办id
	FreeShippingId interface{} // 满包邮ID
	ProductId      interface{} // 产品ID
	ScreeningsId   interface{} // 场次ID
	PriceList      interface{} // 票品列表集合（逗号分隔）
	Status         interface{} // 状态（1.正常 2.已删除）
	CreateDate     *gtime.Time // 创建时间
	UpdateDate     *gtime.Time // 更时间
}
