// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeMessageOrderTimeout is the golang structure of table evente_message_order_timeout for DAO operations like Where/Data.
type EventeMessageOrderTimeout struct {
	g.Meta           `orm:"table:evente_message_order_timeout, do:true"`
	Id               interface{} //
	OrgId            interface{} // org_id
	IncrementId      interface{} // 交易ID
	Status           interface{} // 状态 1 未处理 2 已支付 3 已超时 4 已发送
	OrderDate        *gtime.Time // 下单时间
	ExpiredDate      *gtime.Time // 即将超时时间
	OrderExpiredDate *gtime.Time // 订单超时时间
	CreateDate       *gtime.Time // 新增时间
	UpdateDate       *gtime.Time // 更新时间
	DeleteDate       *gtime.Time // 删除时间
}
