// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeVoucherCode is the golang structure of table evente_voucher_code for DAO operations like Where/Data.
type EventeVoucherCode struct {
	g.Meta             `orm:"table:evente_voucher_code, do:true"`
	Id                 interface{} //
	OrgId              interface{} // 主办id
	Name               interface{} // 优惠码名称
	VoucherCodeType    interface{} // 优惠码类型 1:一人一码 2:通用吗
	MakeCodeType       interface{} // 生成类型 1:系统生成 2:手动导入 3：手动输入
	Number             interface{} // 发行量
	UseNumber          interface{} // 使用量
	CancelledNumber    interface{} // 作废数量
	VoucherType        interface{} // 优惠类型 1:满减 2:折扣
	UseConditionSwitch interface{} // 是否限制使用条件 0不限制 1限制
	UseCondition       interface{} // 使用条件 订单金额满这个数才可使用
	DiscountPercent    interface{} // 折扣比例
	UseStartTime       *gtime.Time // 优惠码使用开始时间
	UseEndTime         *gtime.Time // 优惠码用结束时间
	EventApplyType     interface{} // 适用活动方式 1全部活动 2指定活动参与 3指定活动不参与
	GoodsApplyType     interface{} // 适用商品方式 1全部商品 2指定商品参与 3指定商品不参与
	ProductyId         interface{} // 活动 商品ID序列化
	FetchLimit         interface{} // 每人领取限额
	Status             interface{} // 1-正常，2-删除,3-手动关闭
	CreateDate         *gtime.Time // 新增时间
	UpdateDate         *gtime.Time // 更新时间
	VoucherCodeSubType interface{} // 区分普通/文惠卡
}
