// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeVoucherActivation is the golang structure of table evente_voucher_activation for DAO operations like Where/Data.
type EventeVoucherActivation struct {
	g.Meta            `orm:"table:evente_voucher_activation, do:true"`
	Id                interface{} // 自增id
	OrgId             interface{} // 主办id
	VoucherCodeId     interface{} // 优惠码 主表ID
	ActivationCode    interface{} // 优惠码 号码
	VoucherCodeType   interface{} // 优惠码类型 1:一人一码 2:通用吗
	ActivationType    interface{} // 生成类型 1:系统生成 2:手动导入 3：手动输入
	ActivationDate    *gtime.Time // 使用 作废时间
	ActivationSubType interface{} // 优惠码类型 nomer 普通  wh_card 文惠卡
	Status            interface{} // 使用状态( 1:未使用  2 已使用  3 已作废)
	UnlockStatus      interface{} // 解锁状态
	Remark            interface{} // 备注
	CreateDate        *gtime.Time // 创建时间
	UpdateDate        *gtime.Time //
	InsertSalt        interface{} // 插入盐
}
