// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeReduction is the golang structure of table evente_reduction for DAO operations like Where/Data.
type EventeReduction struct {
	g.Meta        `orm:"table:evente_reduction, do:true"`
	Id            interface{} //
	OrgId         interface{} // org id
	Title         interface{} // 标题
	ReductionMode interface{} // reduction_mode 满减方式(1.满额减免  2.满件减免)
	ReductionType interface{} // reduction_type 满减类型（1.仅按最高减免力度减免一次  2.每满足一次减免一次）
	StartDate     *gtime.Time // 开始时间
	EndDate       *gtime.Time // 结束时间
	CoverImg      interface{} // 封面图ID
	Rule          interface{} // 规则（json 格式数据）
	IsCurrency    interface{} // 是否夸商品优惠（1是 2.否）
	ProductType   interface{} // 适用产品类型（event 演出活动,goods 商品类型）
	ProductList   interface{} // 产品ID集合
	Status        interface{} // 状态（1正常 2.删除）
	CreateDate    *gtime.Time // 创建时间
	UpdateDate    *gtime.Time // 更新时间
}
