// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeIntegralExchange is the golang structure of table evente_integral_exchange for DAO operations like Where/Data.
type EventeIntegralExchange struct {
	g.Meta        `orm:"table:evente_integral_exchange, do:true"`
	Id            interface{} // 自增id
	OrgId         interface{} // 主办id
	DiscountRatio interface{} // 订单折扣比例（1-99整数）
	IntegralRatio interface{} // 积分兑换比例（100积分/1元）
	StartDate     *gtime.Time // 活动开始时间
	StopDate      *gtime.Time // 活动结束时间
	LongTerm      interface{} // 长期有效状态 1有效 2无效
	IntegralUsage interface{} // 积分使用量
	Person        interface{} // 人数
	PersonNumber  interface{} // 人次
	TotalAmount   interface{} // 抵现总金额
	Status        interface{} // 历史数据，1是 2不是
	CreateDate    *gtime.Time // 创建时间
	UpdateDate    *gtime.Time // 修改时间
}
