// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeCouponOrderRel is the golang structure of table evente_coupon_order_rel for DAO operations like Where/Data.
type EventeCouponOrderRel struct {
	g.Meta         `orm:"table:evente_coupon_order_rel, do:true"`
	Id             interface{} //
	OrgId          interface{} //
	UserId         interface{} // 用户id
	UserType       interface{} // 1新用户 2 老用户
	CouponNumberId interface{} // 优惠券number id
	CouponId       interface{} // 优惠券id
	IncrementId    interface{} // 订单increment_id
	PayStatus      interface{} // 支付状态 0 未支付， 1已支付
	OrderMoney     interface{} // 订单金额
	PayMoney       interface{} // 支付金额
	CouponMoney    interface{} // 优惠券金额
	CreateDate     *gtime.Time // 新增时间
	UpdateDate     *gtime.Time // 更新时间
}
