// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeECardActivationExtend is the golang structure of table evente_e_card_activation_extend for DAO operations like Where/Data.
type EventeECardActivationExtend struct {
	g.Meta         `orm:"table:evente_e_card_activation_extend, do:true"`
	Id             interface{} // 自增id
	OrgId          interface{} // 主办id
	UserId         interface{} //
	UserName       interface{} // 用户名
	ActivationId   interface{} // E通卡激活码主表id
	ActivationCode interface{} //
	ActivationDate *gtime.Time // 激活时间(创建时间)
	Status         interface{} // 激活状态( 1: 未激活   2 已激活)
	IdCard         interface{} // 身份证号
	Remark         interface{} // 备注
	AdminName      interface{} // 管理员名称
	CreateDate     *gtime.Time // 激活码创建时间
	UpdateDate     *gtime.Time //
	EndDate        *gtime.Time // 过期时间
	SendStatus     interface{} // 发送状态 1 - 未发送 2 - 已发送
	UserMobile     interface{} // 发送手机号
}
