// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeRegimentExtend is the golang structure of table evente_regiment_extend for DAO operations like Where/Data.
type EventeRegimentExtend struct {
	g.Meta           `orm:"table:evente_regiment_extend, do:true"`
	Id               interface{} // 主键id
	OrgId            interface{} // 主办id
	RegimentId       interface{} // 团id
	GroomStatus      interface{} // 是否开启 推荐拼团 0 - 不开启 1- 开启
	WarmDate         interface{} // 预热时间 小时
	InitJoinNum      interface{} // 初始化参团人数
	SimulationStatus interface{} // 是否开启 模拟开团 0 - 不开启 1- 开启
	Favourable       interface{} // 参加优惠类型  1.积分 2.储值余额 3.优惠券
	CreateDate       *gtime.Time // 下单时间
	UpdateDate       *gtime.Time // 修改时间
}
