// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeRegimentOrder is the golang structure of table evente_regiment_order for DAO operations like Where/Data.
type EventeRegimentOrder struct {
	g.Meta           `orm:"table:evente_regiment_order, do:true"`
	Id               interface{} // 自增id
	OrgId            interface{} // 主办id
	UserId           interface{} // 用户id
	GroupIncrementId interface{} // 团订单id
	IncrementId      interface{} // 主订单id
	RegimentId       interface{} // 团id
	OpenRegimentId   interface{} // 开团id
	Name             interface{} // 购买人名称
	Mobile           interface{} // 手机号
	CountryCode      interface{} // 国别
	OrderMoney       interface{} // 订单总金额
	OrderNumber      interface{} // 购买数量
	OrderState       interface{} // 订单状态 10 待支付 20 已支付 30 已发货 40 已完成 50 订单超时 60 订单取消
	RefundState      interface{} // 0无退款、1 处理中、2退款失败、3 已退款
	OrderType        interface{} // 订单类型(event,goods)
	ProductId        interface{} // 产品id
	ProductTitle     interface{} // 产品名称
	PayWay           interface{} // 支付方式(alipay 支付宝 weixin 微信  free免费订单)
	PayDate          *gtime.Time // 支付时间
	CreateDate       *gtime.Time // 创建时间
	UpdateDate       *gtime.Time // 更新时间
	JoinType         interface{} //
}
