// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeLimitDiscount is the golang structure of table evente_limit_discount for DAO operations like Where/Data.
type EventeLimitDiscount struct {
	g.Meta            `orm:"table:evente_limit_discount, do:true"`
	Id                interface{} // 主键ID
	OrgId             interface{} // 主办ID
	Name              interface{} // 限时折扣名称
	DiscountPercent   interface{} // 限时折扣比例
	DateSwithStatus   interface{} // 日期重复开关  0 - 不启动 1 - 启动
	DateSwithContent  interface{} // 日期重复json串
	MemberLevel       interface{} // 会员级别
	FetchMemberLevel  interface{} // 会员限制 逗号隔开
	FetchMemberSwitch interface{} // 会员限制  0 - 无限制 1 - 限制
	StartDate         *gtime.Time // 开始时间
	EndDate           *gtime.Time // 结束时间
	OrderMoney        interface{} // 下单金额
	Person            interface{} // 参与人数
	PersonNumber      interface{} // 参与人次
	PicUrl            interface{} // 图片url
	WarmDate          interface{} // 折扣预热时间
	DiscountLabel     interface{} // 限时折扣 别名
	FavourableContent interface{} // 下单可抵扣类型 1 - 余额 2 - 积分  逗号隔开
	PurchaseLimit     interface{} // 限购数量
	CreateDate        *gtime.Time // 创建时间
	UpdateDate        *gtime.Time // 创建时间
}
