// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeOpenRegiment is the golang structure of table evente_open_regiment for DAO operations like Where/Data.
type EventeOpenRegiment struct {
	g.Meta              `orm:"table:evente_open_regiment, do:true"`
	Id                  interface{} //
	OrgId               interface{} // 主办id
	RegimentId          interface{} // 团id
	UserId              interface{} // 用户id
	ProductType         interface{} // 产品类型（event 票务 goods 商品）
	ProductId           interface{} // 产品id
	GroupIncrementId    interface{} // 团订单号
	SuccessStatus       interface{} // 是否成团 0 - 未成团 1 - 已成团
	RegimentStatus      interface{} // 拼团状态 0 - 拼团中 1 - 拼团成功 2 - 拼团失败
	OfferedNumber       interface{} // 参团人数
	SuccessRegimentType interface{} // 1 - 普通成团 2- 模拟成团
	RegimentNote        interface{} // 成功(失败)备注
	SuccessRegimentDate *gtime.Time //
	CreateDate          *gtime.Time // 创建时间
	UpdateDate          *gtime.Time // 修改时间
	ExpiryDate          *gtime.Time //
	Pending             interface{} //
}
