// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeIntegralOperationLog is the golang structure of table evente_integral_operation_log for DAO operations like Where/Data.
type EventeIntegralOperationLog struct {
	g.Meta         `orm:"table:evente_integral_operation_log, do:true"`
	Id             interface{} // 自增id
	OrgId          interface{} // 主办id
	BeforeJsonData interface{} // 修改之前操作记录数据
	AfterJsonData  interface{} // 修改之后操作记录数据
	CreateTime     *gtime.Time // 创建时间
}
