// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeVoucherCodeCreateLog is the golang structure of table evente_voucher_code_create_log for DAO operations like Where/Data.
type EventeVoucherCodeCreateLog struct {
	g.Meta         `orm:"table:evente_voucher_code_create_log, do:true"`
	Id             interface{} //
	OrgId          interface{} // 主办id
	VoucherCodeId  interface{} // 主办id
	Total          interface{} // 总数
	Success        interface{} // 成功数量
	Fail           interface{} // 失败数量
	ActivationType interface{} // 生成类型 1:系统生成 2:手动导入 3：手动输入
	FailList       interface{} //
	CreateDate     *gtime.Time // 新增时间
	UpdateDate     *gtime.Time // 更新时间
}
