// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeCouponNumber is the golang structure of table evente_coupon_number for DAO operations like Where/Data.
type EventeCouponNumber struct {
	g.Meta         `orm:"table:evente_coupon_number, do:true"`
	Id             interface{} //
	OrgId          interface{} // 主办id
	UserId         interface{} // 用户id
	CouponId       interface{} // 卡券id
	Status         interface{} // 1正常，2已删除，3已使用
	UseIncrementId interface{} // 使用订单
	UseDate        interface{} // 使用时间
	CouponSource   interface{} // 优惠券来源  normal  普通领取  integral  积分赠送
	CreateDate     *gtime.Time // 新增时间
	UpdateDate     *gtime.Time // 更新时间
}
