// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeECardSale is the golang structure of table evente_e_card_sale for DAO operations like Where/Data.
type EventeECardSale struct {
	g.Meta           `orm:"table:evente_e_card_sale, do:true"`
	Id               interface{} // 自增id
	OrgId            interface{} // 主办id
	UserId           interface{} // 用户id
	IncrementId      interface{} // 订单id
	Price            interface{} // 订单金额
	CardId           interface{} // E通卡id
	Name             interface{} //
	Mobile           interface{} // 手机号
	IdCard           interface{} // 身份证
	PhotoId          interface{} // 照片
	BuyType          interface{} // 购买方式 1直接购买 2 激活码激活
	StartDate        *gtime.Time // 开始时间
	ExpireDate       *gtime.Time // 到期时间
	BeforehandNum    interface{} // 预约次数
	CardWriteStatus  interface{} // 是否写卡 0 - 未写卡 1 - 已写卡
	CardWriteContent interface{} // 年卡卡片写入内容
	CardWriteDate    *gtime.Time // 写卡时间
	CreateDate       *gtime.Time // 创建时间
	UpdateDate       *gtime.Time // 更新时间
	UsableTotal      interface{} // 可预约总次数
	UseUp            interface{} // 是否用完 1是 0 否
	InvalidDate      *gtime.Time // 卡用完时间
}
