// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeIntegralOrderList is the golang structure of table evente_integral_order_list for DAO operations like Where/Data.
type EventeIntegralOrderList struct {
	g.Meta        `orm:"table:evente_integral_order_list, do:true"`
	Id            interface{} // 自增id
	OrgId         interface{} // 主办id
	UserId        interface{} // 用户id
	IntegralId    interface{} // 积分抵现id
	IncrementId   interface{} // 订单id
	Username      interface{} //
	Code          interface{} // 手机区号
	Phone         interface{} // 手机号
	Status        interface{} // 订单状态: 10 待支付 20 已支付 30已发货 40 订单完成 50订单超时 60订单取消 70订单关闭 80 订单异常
	IntegralUsage interface{} // 订单积分使用量
	TotalAmount   interface{} // 抵现总金额
	AmountPayable interface{} // 适用商品应付金额
	DiscountRatio interface{} // 当前订单积分抵现 订单折扣比例快照
	IntegralRatio interface{} // 当前订单积分抵现 积分金额兑换比例
	CreateDate    *gtime.Time //
	UpdateDate    *gtime.Time //
}
