// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeLimitDiscountExtend is the golang structure of table evente_limit_discount_extend for DAO operations like Where/Data.
type EventeLimitDiscountExtend struct {
	g.Meta          `orm:"table:evente_limit_discount_extend, do:true"`
	Id              interface{} // 主键ID
	OrgId           interface{} // 主办ID
	DiscountId      interface{} // 限时折扣ID
	ProductType     interface{} // 产品类型 （event活动 goods商品)
	ProductId       interface{} // 产品id
	ProductName     interface{} // 产品名称
	ScreeningsId    interface{} // 场次ID
	ScreeningsName  interface{} // 场次名称
	PriceList       interface{} // 票品id集合 jason串
	DiscountPercent interface{} // 折扣比例
	GoodsPrice      interface{} // 商品价格
	Status          interface{} // 状态 1正常 2删除 // 预留
	CreateDate      *gtime.Time // 创建时间
	UpdateDate      *gtime.Time // 修改时间
}
