// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeRegiment is the golang structure of table evente_regiment for DAO operations like Where/Data.
type EventeRegiment struct {
	g.Meta          `orm:"table:evente_regiment, do:true"`
	Id              interface{} // 主键id
	OrgId           interface{} // 主办id
	Title           interface{} // 名称
	RegimentType    interface{} // 拼团类型 0 - 普通团 1 - 新人团 2 - 抽奖团
	StartDate       *gtime.Time // 开始时间
	EndDate         *gtime.Time // 结束时间
	RegimentPeople  interface{} // 成团人数
	ExpiryDate      interface{} // 有效期
	ProductId       interface{} // 产品id
	ProductType     interface{} // 产品类型 event - 活动 goods - 商品
	LimitNum        interface{} // 单次购买上限
	OpenRegimentNum interface{} // 开团次数
	JoinRegimentNum interface{} // 参团次数
	RegimentStatus  interface{} // 拼团状态 1 - 正常 0 - 关闭
	IsDel           interface{} // 逻辑删除状态：默认 0 未删除  1 - 已删除
	CreateType      interface{} // 创建类型 0 - h5 1 - 小程序
	CreateDate      *gtime.Time // 创建时间
	DeleteDate      *gtime.Time // 删除时间
	UpdateDate      *gtime.Time // 修改时间
	EndHandleStatus interface{} // 活动结束处理状态 -1 有待支付 0 未处理 1 已处理
}
