// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeLimitDiscountOrder is the golang structure of table evente_limit_discount_order for DAO operations like Where/Data.
type EventeLimitDiscountOrder struct {
	g.Meta           `orm:"table:evente_limit_discount_order, do:true"`
	Id               interface{} // 自增ID
	OrgId            interface{} // 主办ID
	UserId           interface{} // C端用户ID
	IncrementId      interface{} // 订单ID
	DiscountId       interface{} // 限时折扣id
	Name             interface{} // 姓名
	Code             interface{} // 手机区号
	Phone            interface{} // 手机号
	ProductType      interface{} // 产品类型 （event活动 goods商品)
	ProductId        interface{} // 产品id
	ScreeningsId     interface{} // 场次id,只在product_type=event 时有效
	OrderMoney       interface{} // 下单金额
	UseLimitDiscount interface{} // 商品折扣
	AmountPayable    interface{} // (适用商品应付金额)
	Status           interface{} // 订单状态: 20 已支付 60订单取消
	CreateDate       *gtime.Time // 创建时间
	UpdateDate       *gtime.Time // 修改时间
	BuyNumber        interface{} //
}
