// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// EventeIntegralOperationLogDao is the data access object for table evente_integral_operation_log.
type EventeIntegralOperationLogDao struct {
	table   string                            // table is the underlying table name of the DAO.
	group   string                            // group is the database configuration group name of current DAO.
	columns EventeIntegralOperationLogColumns // columns contains all the column names of Table for convenient usage.
}

// EventeIntegralOperationLogColumns defines and stores column names for table evente_integral_operation_log.
type EventeIntegralOperationLogColumns struct {
	Id             string // 自增id
	OrgId          string // 主办id
	BeforeJsonData string // 修改之前操作记录数据
	AfterJsonData  string // 修改之后操作记录数据
	CreateTime     string // 创建时间
}

// eventeIntegralOperationLogColumns holds the columns for table evente_integral_operation_log.
var eventeIntegralOperationLogColumns = EventeIntegralOperationLogColumns{
	Id:             "id",
	OrgId:          "org_id",
	BeforeJsonData: "before_json_data",
	AfterJsonData:  "after_json_data",
	CreateTime:     "create_time",
}

// NewEventeIntegralOperationLogDao creates and returns a new DAO object for table data access.
func NewEventeIntegralOperationLogDao() *EventeIntegralOperationLogDao {
	return &EventeIntegralOperationLogDao{
		group:   "default",
		table:   "evente_integral_operation_log",
		columns: eventeIntegralOperationLogColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *EventeIntegralOperationLogDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *EventeIntegralOperationLogDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *EventeIntegralOperationLogDao) Columns() EventeIntegralOperationLogColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *EventeIntegralOperationLogDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *EventeIntegralOperationLogDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *EventeIntegralOperationLogDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
