
# GoFrame CLI tool configuration.
gfcli:
  gen:
    dao:
    - link:            "mysql:root:1111111q@tcp(127.0.0.1:3306)/em_markting"
      removePrefix:    "gf_"
      descriptionTag:  true
      noModelComment:  true
