// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"golang8090/internal/model"
)

type (
	ICard interface {
		Create(ctx context.Context, in model.CardCreateInput) (out bool, err error)
		GetList(ctx context.Context, in model.CardGetListInput) (out *model.CardGetListOutput, err error)
	}
)

var (
	localCard ICard
)

func Card() ICard {
	if localCard == nil {
		panic("implement not found for interface ICard, forgot register?")
	}
	return localCard
}

func RegisterCard(i ICard) {
	localCard = i
}
