// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeCouponOrderRelDao is internal type for wrapping internal DAO implements.
type internalEventeCouponOrderRelDao = *internal.EventeCouponOrderRelDao

// eventeCouponOrderRelDao is the data access object for table evente_coupon_order_rel.
// You can define custom methods on it to extend its functionality as you wish.
type eventeCouponOrderRelDao struct {
	internalEventeCouponOrderRelDao
}

var (
	// EventeCouponOrderRel is globally public accessible object for table evente_coupon_order_rel operations.
	EventeCouponOrderRel = eventeCouponOrderRelDao{
		internal.NewEventeCouponOrderRelDao(),
	}
)

// Fill with you ideas below.
