// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeRegimentStockDao is internal type for wrapping internal DAO implements.
type internalEventeRegimentStockDao = *internal.EventeRegimentStockDao

// eventeRegimentStockDao is the data access object for table evente_regiment_stock.
// You can define custom methods on it to extend its functionality as you wish.
type eventeRegimentStockDao struct {
	internalEventeRegimentStockDao
}

var (
	// EventeRegimentStock is globally public accessible object for table evente_regiment_stock operations.
	EventeRegimentStock = eventeRegimentStockDao{
		internal.NewEventeRegimentStockDao(),
	}
)

// Fill with you ideas below.
