// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeIntegralOperationLogDao is internal type for wrapping internal DAO implements.
type internalEventeIntegralOperationLogDao = *internal.EventeIntegralOperationLogDao

// eventeIntegralOperationLogDao is the data access object for table evente_integral_operation_log.
// You can define custom methods on it to extend its functionality as you wish.
type eventeIntegralOperationLogDao struct {
	internalEventeIntegralOperationLogDao
}

var (
	// EventeIntegralOperationLog is globally public accessible object for table evente_integral_operation_log operations.
	EventeIntegralOperationLog = eventeIntegralOperationLogDao{
		internal.NewEventeIntegralOperationLogDao(),
	}
)

// Fill with you ideas below.
