// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeOpenRegimentDao is internal type for wrapping internal DAO implements.
type internalEventeOpenRegimentDao = *internal.EventeOpenRegimentDao

// eventeOpenRegimentDao is the data access object for table evente_open_regiment.
// You can define custom methods on it to extend its functionality as you wish.
type eventeOpenRegimentDao struct {
	internalEventeOpenRegimentDao
}

var (
	// EventeOpenRegiment is globally public accessible object for table evente_open_regiment operations.
	EventeOpenRegiment = eventeOpenRegimentDao{
		internal.NewEventeOpenRegimentDao(),
	}
)

// Fill with you ideas below.
