// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeECardSaleGoodsDao is internal type for wrapping internal DAO implements.
type internalEventeECardSaleGoodsDao = *internal.EventeECardSaleGoodsDao

// eventeECardSaleGoodsDao is the data access object for table evente_e_card_sale_goods.
// You can define custom methods on it to extend its functionality as you wish.
type eventeECardSaleGoodsDao struct {
	internalEventeECardSaleGoodsDao
}

var (
	// EventeECardSaleGoods is globally public accessible object for table evente_e_card_sale_goods operations.
	EventeECardSaleGoods = eventeECardSaleGoodsDao{
		internal.NewEventeECardSaleGoodsDao(),
	}
)

// Fill with you ideas below.
