// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeLimitDiscountOrderDao is internal type for wrapping internal DAO implements.
type internalEventeLimitDiscountOrderDao = *internal.EventeLimitDiscountOrderDao

// eventeLimitDiscountOrderDao is the data access object for table evente_limit_discount_order.
// You can define custom methods on it to extend its functionality as you wish.
type eventeLimitDiscountOrderDao struct {
	internalEventeLimitDiscountOrderDao
}

var (
	// EventeLimitDiscountOrder is globally public accessible object for table evente_limit_discount_order operations.
	EventeLimitDiscountOrder = eventeLimitDiscountOrderDao{
		internal.NewEventeLimitDiscountOrderDao(),
	}
)

// Fill with you ideas below.
