// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeCouponExtendDao is internal type for wrapping internal DAO implements.
type internalEventeCouponExtendDao = *internal.EventeCouponExtendDao

// eventeCouponExtendDao is the data access object for table evente_coupon_extend.
// You can define custom methods on it to extend its functionality as you wish.
type eventeCouponExtendDao struct {
	internalEventeCouponExtendDao
}

var (
	// EventeCouponExtend is globally public accessible object for table evente_coupon_extend operations.
	EventeCouponExtend = eventeCouponExtendDao{
		internal.NewEventeCouponExtendDao(),
	}
)

// Fill with you ideas below.
