// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeECardActivationExtendDao is internal type for wrapping internal DAO implements.
type internalEventeECardActivationExtendDao = *internal.EventeECardActivationExtendDao

// eventeECardActivationExtendDao is the data access object for table evente_e_card_activation_extend.
// You can define custom methods on it to extend its functionality as you wish.
type eventeECardActivationExtendDao struct {
	internalEventeECardActivationExtendDao
}

var (
	// EventeECardActivationExtend is globally public accessible object for table evente_e_card_activation_extend operations.
	EventeECardActivationExtend = eventeECardActivationExtendDao{
		internal.NewEventeECardActivationExtendDao(),
	}
)

// Fill with you ideas below.
