// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeECardAppointmentPriceRelDao is internal type for wrapping internal DAO implements.
type internalEventeECardAppointmentPriceRelDao = *internal.EventeECardAppointmentPriceRelDao

// eventeECardAppointmentPriceRelDao is the data access object for table evente_e_card_appointment_price_rel.
// You can define custom methods on it to extend its functionality as you wish.
type eventeECardAppointmentPriceRelDao struct {
	internalEventeECardAppointmentPriceRelDao
}

var (
	// EventeECardAppointmentPriceRel is globally public accessible object for table evente_e_card_appointment_price_rel operations.
	EventeECardAppointmentPriceRel = eventeECardAppointmentPriceRelDao{
		internal.NewEventeECardAppointmentPriceRelDao(),
	}
)

// Fill with you ideas below.
