// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeVoucherCodeDao is internal type for wrapping internal DAO implements.
type internalEventeVoucherCodeDao = *internal.EventeVoucherCodeDao

// eventeVoucherCodeDao is the data access object for table evente_voucher_code.
// You can define custom methods on it to extend its functionality as you wish.
type eventeVoucherCodeDao struct {
	internalEventeVoucherCodeDao
}

var (
	// EventeVoucherCode is globally public accessible object for table evente_voucher_code operations.
	EventeVoucherCode = eventeVoucherCodeDao{
		internal.NewEventeVoucherCodeDao(),
	}
)

// Fill with you ideas below.
