// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeSuperSmallProgramAuthDao is internal type for wrapping internal DAO implements.
type internalEventeSuperSmallProgramAuthDao = *internal.EventeSuperSmallProgramAuthDao

// eventeSuperSmallProgramAuthDao is the data access object for table evente_super_small_program_auth.
// You can define custom methods on it to extend its functionality as you wish.
type eventeSuperSmallProgramAuthDao struct {
	internalEventeSuperSmallProgramAuthDao
}

var (
	// EventeSuperSmallProgramAuth is globally public accessible object for table evente_super_small_program_auth operations.
	EventeSuperSmallProgramAuth = eventeSuperSmallProgramAuthDao{
		internal.NewEventeSuperSmallProgramAuthDao(),
	}
)

// Fill with you ideas below.
