// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeVoucherCodeOrderRelDao is internal type for wrapping internal DAO implements.
type internalEventeVoucherCodeOrderRelDao = *internal.EventeVoucherCodeOrderRelDao

// eventeVoucherCodeOrderRelDao is the data access object for table evente_voucher_code_order_rel.
// You can define custom methods on it to extend its functionality as you wish.
type eventeVoucherCodeOrderRelDao struct {
	internalEventeVoucherCodeOrderRelDao
}

var (
	// EventeVoucherCodeOrderRel is globally public accessible object for table evente_voucher_code_order_rel operations.
	EventeVoucherCodeOrderRel = eventeVoucherCodeOrderRelDao{
		internal.NewEventeVoucherCodeOrderRelDao(),
	}
)

// Fill with you ideas below.
