// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeRegimentDao is internal type for wrapping internal DAO implements.
type internalEventeRegimentDao = *internal.EventeRegimentDao

// eventeRegimentDao is the data access object for table evente_regiment.
// You can define custom methods on it to extend its functionality as you wish.
type eventeRegimentDao struct {
	internalEventeRegimentDao
}

var (
	// EventeRegiment is globally public accessible object for table evente_regiment operations.
	EventeRegiment = eventeRegimentDao{
		internal.NewEventeRegimentDao(),
	}
)

// Fill with you ideas below.
