// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeOrgPartyAuthDao is internal type for wrapping internal DAO implements.
type internalEventeOrgPartyAuthDao = *internal.EventeOrgPartyAuthDao

// eventeOrgPartyAuthDao is the data access object for table evente_org_party_auth.
// You can define custom methods on it to extend its functionality as you wish.
type eventeOrgPartyAuthDao struct {
	internalEventeOrgPartyAuthDao
}

var (
	// EventeOrgPartyAuth is globally public accessible object for table evente_org_party_auth operations.
	EventeOrgPartyAuth = eventeOrgPartyAuthDao{
		internal.NewEventeOrgPartyAuthDao(),
	}
)

// Fill with you ideas below.
