// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeECardAppointmentDao is internal type for wrapping internal DAO implements.
type internalEventeECardAppointmentDao = *internal.EventeECardAppointmentDao

// eventeECardAppointmentDao is the data access object for table evente_e_card_appointment.
// You can define custom methods on it to extend its functionality as you wish.
type eventeECardAppointmentDao struct {
	internalEventeECardAppointmentDao
}

var (
	// EventeECardAppointment is globally public accessible object for table evente_e_card_appointment operations.
	EventeECardAppointment = eventeECardAppointmentDao{
		internal.NewEventeECardAppointmentDao(),
	}
)

// Fill with you ideas below.
