// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeOrgWechatAuthDao is internal type for wrapping internal DAO implements.
type internalEventeOrgWechatAuthDao = *internal.EventeOrgWechatAuthDao

// eventeOrgWechatAuthDao is the data access object for table evente_org_wechat_auth.
// You can define custom methods on it to extend its functionality as you wish.
type eventeOrgWechatAuthDao struct {
	internalEventeOrgWechatAuthDao
}

var (
	// EventeOrgWechatAuth is globally public accessible object for table evente_org_wechat_auth operations.
	EventeOrgWechatAuth = eventeOrgWechatAuthDao{
		internal.NewEventeOrgWechatAuthDao(),
	}
)

// Fill with you ideas below.
