// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeCouponNumberDao is internal type for wrapping internal DAO implements.
type internalEventeCouponNumberDao = *internal.EventeCouponNumberDao

// eventeCouponNumberDao is the data access object for table evente_coupon_number.
// You can define custom methods on it to extend its functionality as you wish.
type eventeCouponNumberDao struct {
	internalEventeCouponNumberDao
}

var (
	// EventeCouponNumber is globally public accessible object for table evente_coupon_number operations.
	EventeCouponNumber = eventeCouponNumberDao{
		internal.NewEventeCouponNumberDao(),
	}
)

// Fill with you ideas below.
