// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeReductionDao is internal type for wrapping internal DAO implements.
type internalEventeReductionDao = *internal.EventeReductionDao

// eventeReductionDao is the data access object for table evente_reduction.
// You can define custom methods on it to extend its functionality as you wish.
type eventeReductionDao struct {
	internalEventeReductionDao
}

var (
	// EventeReduction is globally public accessible object for table evente_reduction operations.
	EventeReduction = eventeReductionDao{
		internal.NewEventeReductionDao(),
	}
)

// Fill with you ideas below.
