// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeOrgPushConfDao is internal type for wrapping internal DAO implements.
type internalEventeOrgPushConfDao = *internal.EventeOrgPushConfDao

// eventeOrgPushConfDao is the data access object for table evente_org_push_conf.
// You can define custom methods on it to extend its functionality as you wish.
type eventeOrgPushConfDao struct {
	internalEventeOrgPushConfDao
}

var (
	// EventeOrgPushConf is globally public accessible object for table evente_org_push_conf operations.
	EventeOrgPushConf = eventeOrgPushConfDao{
		internal.NewEventeOrgPushConfDao(),
	}
)

// Fill with you ideas below.
