// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeVoucherCodeCreateLogDao is internal type for wrapping internal DAO implements.
type internalEventeVoucherCodeCreateLogDao = *internal.EventeVoucherCodeCreateLogDao

// eventeVoucherCodeCreateLogDao is the data access object for table evente_voucher_code_create_log.
// You can define custom methods on it to extend its functionality as you wish.
type eventeVoucherCodeCreateLogDao struct {
	internalEventeVoucherCodeCreateLogDao
}

var (
	// EventeVoucherCodeCreateLog is globally public accessible object for table evente_voucher_code_create_log operations.
	EventeVoucherCodeCreateLog = eventeVoucherCodeCreateLogDao{
		internal.NewEventeVoucherCodeCreateLogDao(),
	}
)

// Fill with you ideas below.
