// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeFreeShippingProductEventDao is internal type for wrapping internal DAO implements.
type internalEventeFreeShippingProductEventDao = *internal.EventeFreeShippingProductEventDao

// eventeFreeShippingProductEventDao is the data access object for table evente_free_shipping_product_event.
// You can define custom methods on it to extend its functionality as you wish.
type eventeFreeShippingProductEventDao struct {
	internalEventeFreeShippingProductEventDao
}

var (
	// EventeFreeShippingProductEvent is globally public accessible object for table evente_free_shipping_product_event operations.
	EventeFreeShippingProductEvent = eventeFreeShippingProductEventDao{
		internal.NewEventeFreeShippingProductEventDao(),
	}
)

// Fill with you ideas below.
