// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeECardDelayLogDao is internal type for wrapping internal DAO implements.
type internalEventeECardDelayLogDao = *internal.EventeECardDelayLogDao

// eventeECardDelayLogDao is the data access object for table evente_e_card_delay_log.
// You can define custom methods on it to extend its functionality as you wish.
type eventeECardDelayLogDao struct {
	internalEventeECardDelayLogDao
}

var (
	// EventeECardDelayLog is globally public accessible object for table evente_e_card_delay_log operations.
	EventeECardDelayLog = eventeECardDelayLogDao{
		internal.NewEventeECardDelayLogDao(),
	}
)

// Fill with you ideas below.
