// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeOrgPartyReleaseDao is internal type for wrapping internal DAO implements.
type internalEventeOrgPartyReleaseDao = *internal.EventeOrgPartyReleaseDao

// eventeOrgPartyReleaseDao is the data access object for table evente_org_party_release.
// You can define custom methods on it to extend its functionality as you wish.
type eventeOrgPartyReleaseDao struct {
	internalEventeOrgPartyReleaseDao
}

var (
	// EventeOrgPartyRelease is globally public accessible object for table evente_org_party_release operations.
	EventeOrgPartyRelease = eventeOrgPartyReleaseDao{
		internal.NewEventeOrgPartyReleaseDao(),
	}
)

// Fill with you ideas below.
