// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeECardLogDao is internal type for wrapping internal DAO implements.
type internalEventeECardLogDao = *internal.EventeECardLogDao

// eventeECardLogDao is the data access object for table evente_e_card_log.
// You can define custom methods on it to extend its functionality as you wish.
type eventeECardLogDao struct {
	internalEventeECardLogDao
}

var (
	// EventeECardLog is globally public accessible object for table evente_e_card_log operations.
	EventeECardLog = eventeECardLogDao{
		internal.NewEventeECardLogDao(),
	}
)

// Fill with you ideas below.
