// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeFreeShippingDao is internal type for wrapping internal DAO implements.
type internalEventeFreeShippingDao = *internal.EventeFreeShippingDao

// eventeFreeShippingDao is the data access object for table evente_free_shipping.
// You can define custom methods on it to extend its functionality as you wish.
type eventeFreeShippingDao struct {
	internalEventeFreeShippingDao
}

var (
	// EventeFreeShipping is globally public accessible object for table evente_free_shipping operations.
	EventeFreeShipping = eventeFreeShippingDao{
		internal.NewEventeFreeShippingDao(),
	}
)

// Fill with you ideas below.
