// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeIntegralExchangeDao is internal type for wrapping internal DAO implements.
type internalEventeIntegralExchangeDao = *internal.EventeIntegralExchangeDao

// eventeIntegralExchangeDao is the data access object for table evente_integral_exchange.
// You can define custom methods on it to extend its functionality as you wish.
type eventeIntegralExchangeDao struct {
	internalEventeIntegralExchangeDao
}

var (
	// EventeIntegralExchange is globally public accessible object for table evente_integral_exchange operations.
	EventeIntegralExchange = eventeIntegralExchangeDao{
		internal.NewEventeIntegralExchangeDao(),
	}
)

// Fill with you ideas below.
