// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeECardSaleDao is internal type for wrapping internal DAO implements.
type internalEventeECardSaleDao = *internal.EventeECardSaleDao

// eventeECardSaleDao is the data access object for table evente_e_card_sale.
// You can define custom methods on it to extend its functionality as you wish.
type eventeECardSaleDao struct {
	internalEventeECardSaleDao
}

var (
	// EventeECardSale is globally public accessible object for table evente_e_card_sale operations.
	EventeECardSale = eventeECardSaleDao{
		internal.NewEventeECardSaleDao(),
	}
)

// Fill with you ideas below.
