// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeRegimentOrderDao is internal type for wrapping internal DAO implements.
type internalEventeRegimentOrderDao = *internal.EventeRegimentOrderDao

// eventeRegimentOrderDao is the data access object for table evente_regiment_order.
// You can define custom methods on it to extend its functionality as you wish.
type eventeRegimentOrderDao struct {
	internalEventeRegimentOrderDao
}

var (
	// EventeRegimentOrder is globally public accessible object for table evente_regiment_order operations.
	EventeRegimentOrder = eventeRegimentOrderDao{
		internal.NewEventeRegimentOrderDao(),
	}
)

// Fill with you ideas below.
