// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeMessageOrderTimeoutDao is internal type for wrapping internal DAO implements.
type internalEventeMessageOrderTimeoutDao = *internal.EventeMessageOrderTimeoutDao

// eventeMessageOrderTimeoutDao is the data access object for table evente_message_order_timeout.
// You can define custom methods on it to extend its functionality as you wish.
type eventeMessageOrderTimeoutDao struct {
	internalEventeMessageOrderTimeoutDao
}

var (
	// EventeMessageOrderTimeout is globally public accessible object for table evente_message_order_timeout operations.
	EventeMessageOrderTimeout = eventeMessageOrderTimeoutDao{
		internal.NewEventeMessageOrderTimeoutDao(),
	}
)

// Fill with you ideas below.
