// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeLimitDiscountLogDao is internal type for wrapping internal DAO implements.
type internalEventeLimitDiscountLogDao = *internal.EventeLimitDiscountLogDao

// eventeLimitDiscountLogDao is the data access object for table evente_limit_discount_log.
// You can define custom methods on it to extend its functionality as you wish.
type eventeLimitDiscountLogDao struct {
	internalEventeLimitDiscountLogDao
}

var (
	// EventeLimitDiscountLog is globally public accessible object for table evente_limit_discount_log operations.
	EventeLimitDiscountLog = eventeLimitDiscountLogDao{
		internal.NewEventeLimitDiscountLogDao(),
	}
)

// Fill with you ideas below.
