// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"golang8090/internal/dao/internal"
)

// internalEventeSuperSmallProgramReleaseDao is internal type for wrapping internal DAO implements.
type internalEventeSuperSmallProgramReleaseDao = *internal.EventeSuperSmallProgramReleaseDao

// eventeSuperSmallProgramReleaseDao is the data access object for table evente_super_small_program_release.
// You can define custom methods on it to extend its functionality as you wish.
type eventeSuperSmallProgramReleaseDao struct {
	internalEventeSuperSmallProgramReleaseDao
}

var (
	// EventeSuperSmallProgramRelease is globally public accessible object for table evente_super_small_program_release operations.
	EventeSuperSmallProgramRelease = eventeSuperSmallProgramReleaseDao{
		internal.NewEventeSuperSmallProgramReleaseDao(),
	}
)

// Fill with you ideas below.
