// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeReduction is the golang structure for table evente_reduction.
type EventeReduction struct {
	Id            uint        `json:"id"            description:""`
	OrgId         int         `json:"orgId"         description:"org id"`
	Title         string      `json:"title"         description:"标题"`
	ReductionMode int         `json:"reductionMode" description:"reduction_mode 满减方式(1.满额减免  2.满件减免)"`
	ReductionType int         `json:"reductionType" description:"reduction_type 满减类型（1.仅按最高减免力度减免一次  2.每满足一次减免一次）"`
	StartDate     *gtime.Time `json:"startDate"     description:"开始时间"`
	EndDate       *gtime.Time `json:"endDate"       description:"结束时间"`
	CoverImg      int         `json:"coverImg"      description:"封面图ID"`
	Rule          string      `json:"rule"          description:"规则（json 格式数据）"`
	IsCurrency    int         `json:"isCurrency"    description:"是否夸商品优惠（1是 2.否）"`
	ProductType   string      `json:"productType"   description:"适用产品类型（event 演出活动,goods 商品类型）"`
	ProductList   string      `json:"productList"   description:"产品ID集合"`
	Status        int         `json:"status"        description:"状态（1正常 2.删除）"`
	CreateDate    *gtime.Time `json:"createDate"    description:"创建时间"`
	UpdateDate    *gtime.Time `json:"updateDate"    description:"更新时间"`
}
