// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeLimitDiscount is the golang structure for table evente_limit_discount.
type EventeLimitDiscount struct {
	Id                uint        `json:"id"                description:"主键ID"`
	OrgId             int         `json:"orgId"             description:"主办ID"`
	Name              string      `json:"name"              description:"限时折扣名称"`
	DiscountPercent   uint        `json:"discountPercent"   description:"限时折扣比例"`
	DateSwithStatus   int         `json:"dateSwithStatus"   description:"日期重复开关  0 - 不启动 1 - 启动"`
	DateSwithContent  string      `json:"dateSwithContent"  description:"日期重复json串"`
	MemberLevel       int         `json:"memberLevel"       description:"会员级别"`
	FetchMemberLevel  string      `json:"fetchMemberLevel"  description:"会员限制 逗号隔开"`
	FetchMemberSwitch int         `json:"fetchMemberSwitch" description:"会员限制  0 - 无限制 1 - 限制"`
	StartDate         *gtime.Time `json:"startDate"         description:"开始时间"`
	EndDate           *gtime.Time `json:"endDate"           description:"结束时间"`
	OrderMoney        float64     `json:"orderMoney"        description:"下单金额"`
	Person            uint        `json:"person"            description:"参与人数"`
	PersonNumber      uint        `json:"personNumber"      description:"参与人次"`
	PicUrl            string      `json:"picUrl"            description:"图片url"`
	WarmDate          int         `json:"warmDate"          description:"折扣预热时间"`
	DiscountLabel     string      `json:"discountLabel"     description:"限时折扣 别名"`
	FavourableContent string      `json:"favourableContent" description:"下单可抵扣类型 1 - 余额 2 - 积分  逗号隔开"`
	PurchaseLimit     int         `json:"purchaseLimit"     description:"限购数量"`
	CreateDate        *gtime.Time `json:"createDate"        description:"创建时间"`
	UpdateDate        *gtime.Time `json:"updateDate"        description:"创建时间"`
}
