// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeRegimentExtend is the golang structure for table evente_regiment_extend.
type EventeRegimentExtend struct {
	Id               uint        `json:"id"               description:"主键id"`
	OrgId            uint        `json:"orgId"            description:"主办id"`
	RegimentId       uint        `json:"regimentId"       description:"团id"`
	GroomStatus      int         `json:"groomStatus"      description:"是否开启 推荐拼团 0 - 不开启 1- 开启"`
	WarmDate         int         `json:"warmDate"         description:"预热时间 小时"`
	InitJoinNum      int         `json:"initJoinNum"      description:"初始化参团人数"`
	SimulationStatus int         `json:"simulationStatus" description:"是否开启 模拟开团 0 - 不开启 1- 开启"`
	Favourable       string      `json:"favourable"       description:"参加优惠类型  1.积分 2.储值余额 3.优惠券"`
	CreateDate       *gtime.Time `json:"createDate"       description:"下单时间"`
	UpdateDate       *gtime.Time `json:"updateDate"       description:"修改时间"`
}
