// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeECardSale is the golang structure for table evente_e_card_sale.
type EventeECardSale struct {
	Id               int         `json:"id"               description:"自增id"`
	OrgId            uint        `json:"orgId"            description:"主办id"`
	UserId           uint        `json:"userId"           description:"用户id"`
	IncrementId      string      `json:"incrementId"      description:"订单id"`
	Price            float64     `json:"price"            description:"订单金额"`
	CardId           int         `json:"cardId"           description:"E通卡id"`
	Name             string      `json:"name"             description:""`
	Mobile           string      `json:"mobile"           description:"手机号"`
	IdCard           string      `json:"idCard"           description:"身份证"`
	PhotoId          int         `json:"photoId"          description:"照片"`
	BuyType          uint        `json:"buyType"          description:"购买方式 1直接购买 2 激活码激活"`
	StartDate        *gtime.Time `json:"startDate"        description:"开始时间"`
	ExpireDate       *gtime.Time `json:"expireDate"       description:"到期时间"`
	BeforehandNum    uint        `json:"beforehandNum"    description:"预约次数"`
	CardWriteStatus  int         `json:"cardWriteStatus"  description:"是否写卡 0 - 未写卡 1 - 已写卡"`
	CardWriteContent string      `json:"cardWriteContent" description:"年卡卡片写入内容"`
	CardWriteDate    *gtime.Time `json:"cardWriteDate"    description:"写卡时间"`
	CreateDate       *gtime.Time `json:"createDate"       description:"创建时间"`
	UpdateDate       *gtime.Time `json:"updateDate"       description:"更新时间"`
	UsableTotal      uint        `json:"usableTotal"      description:"可预约总次数"`
	UseUp            uint        `json:"useUp"            description:"是否用完 1是 0 否"`
	InvalidDate      *gtime.Time `json:"invalidDate"      description:"卡用完时间"`
}
