// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeCouponOrderRel is the golang structure for table evente_coupon_order_rel.
type EventeCouponOrderRel struct {
	Id             uint64      `json:"id"             description:""`
	OrgId          int64       `json:"orgId"          description:""`
	UserId         int64       `json:"userId"         description:"用户id"`
	UserType       int         `json:"userType"       description:"1新用户 2 老用户"`
	CouponNumberId int64       `json:"couponNumberId" description:"优惠券number id"`
	CouponId       int64       `json:"couponId"       description:"优惠券id"`
	IncrementId    string      `json:"incrementId"    description:"订单increment_id"`
	PayStatus      int         `json:"payStatus"      description:"支付状态 0 未支付， 1已支付"`
	OrderMoney     float64     `json:"orderMoney"     description:"订单金额"`
	PayMoney       float64     `json:"payMoney"       description:"支付金额"`
	CouponMoney    float64     `json:"couponMoney"    description:"优惠券金额"`
	CreateDate     *gtime.Time `json:"createDate"     description:"新增时间"`
	UpdateDate     *gtime.Time `json:"updateDate"     description:"更新时间"`
}
