// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeECardActivation is the golang structure for table evente_e_card_activation.
type EventeECardActivation struct {
	Id               uint        `json:"id"               description:"自增id"`
	OrgId            uint        `json:"orgId"            description:"主办id"`
	CardId           uint        `json:"cardId"           description:"E通卡id"`
	Number           uint        `json:"number"           description:"生成数量"`
	ActivationNumber uint        `json:"activationNumber" description:"激活数量"`
	CreateDate       *gtime.Time `json:"createDate"       description:"生成时间(创建时间)"`
	UpdateDate       *gtime.Time `json:"updateDate"       description:"更新时间"`
}
