// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeVoucherCodeOrderRel is the golang structure for table evente_voucher_code_order_rel.
type EventeVoucherCodeOrderRel struct {
	Id                  uint64      `json:"id"                  description:""`
	OrgId               int64       `json:"orgId"               description:""`
	UserId              int64       `json:"userId"              description:"用户id"`
	VoucherActivationId int64       `json:"voucherActivationId" description:"优惠码明细ID"`
	VoucherCodeId       int64       `json:"voucherCodeId"       description:"主表ID"`
	IncrementId         string      `json:"incrementId"         description:"订单increment_id"`
	PayStatus           int         `json:"payStatus"           description:"支付状态 0 未支付， 1已支付 2 退款"`
	OrderMoney          float64     `json:"orderMoney"          description:"订单金额"`
	PayMoney            float64     `json:"payMoney"            description:"支付金额"`
	VoucherCodeMoney    float64     `json:"voucherCodeMoney"    description:"优惠金额"`
	CreateDate          *gtime.Time `json:"createDate"          description:"新增时间"`
	UpdateDate          *gtime.Time `json:"updateDate"          description:"更新时间"`
	ActivationCode      string      `json:"activationCode"      description:"优惠码"`
	UserType            int         `json:"userType"            description:"1新用户 2 老用户"`
	UserName            string      `json:"userName"            description:""`
	Mobile              string      `json:"mobile"              description:"手机号"`
	CheckStatus         int         `json:"checkStatus"         description:"核销状态 0 未核销 1 核销成功  2 核销失败"`
	CheckMesaage        string      `json:"checkMesaage"        description:"核销成功 失败原因"`
}
