// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeECardAppointment is the golang structure for table evente_e_card_appointment.
type EventeECardAppointment struct {
	Id                  uint        `json:"id"                  description:"自增id"`
	IncrementId         string      `json:"incrementId"         description:""`
	UserId              uint        `json:"userId"              description:"C端用户id"`
	OrgId               int         `json:"orgId"               description:"主办id"`
	Mobile              string      `json:"mobile"              description:"手机号"`
	Name                string      `json:"name"                description:"预约联系人"`
	CardId              int         `json:"cardId"              description:"E通卡id"`
	CardSaleId          uint        `json:"cardSaleId"          description:""`
	PicId               uint        `json:"picId"               description:"活动图片id"`
	EventeId            int         `json:"eventeId"            description:"活动id"`
	EventeName          string      `json:"eventeName"          description:"活动名称"`
	ScreeningsId        int         `json:"screeningsId"        description:"场次id"`
	ScreeningsName      string      `json:"screeningsName"      description:"场次名称"`
	ScreeningsStartDate *gtime.Time `json:"screeningsStartDate" description:"场次开始时间"`
	ScreeningsEndDate   *gtime.Time `json:"screeningsEndDate"   description:"场次结束时间"`
	Number              uint        `json:"number"              description:"预约数量"`
	Status              int         `json:"status"              description:"状态 1预约 2取消预约 3已核销"`
	VerificationName    string      `json:"verificationName"    description:"核销人-主办名称"`
	VerificationDate    *gtime.Time `json:"verificationDate"    description:"核销时间"`
	CreateDate          *gtime.Time `json:"createDate"          description:"创建时间"`
	UpdateDate          *gtime.Time `json:"updateDate"          description:"修改时间"`
	UseNumber           uint        `json:"useNumber"           description:"本次消耗年卡次数"`
}
