// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeVoucherCode is the golang structure for table evente_voucher_code.
type EventeVoucherCode struct {
	Id                 uint64      `json:"id"                 description:""`
	OrgId              int64       `json:"orgId"              description:"主办id"`
	Name               string      `json:"name"               description:"优惠码名称"`
	VoucherCodeType    int         `json:"voucherCodeType"    description:"优惠码类型 1:一人一码 2:通用吗"`
	MakeCodeType       int         `json:"makeCodeType"       description:"生成类型 1:系统生成 2:手动导入 3：手动输入"`
	Number             int         `json:"number"             description:"发行量"`
	UseNumber          int         `json:"useNumber"          description:"使用量"`
	CancelledNumber    int         `json:"cancelledNumber"    description:"作废数量"`
	VoucherType        int         `json:"voucherType"        description:"优惠类型 1:满减 2:折扣"`
	UseConditionSwitch int         `json:"useConditionSwitch" description:"是否限制使用条件 0不限制 1限制"`
	UseCondition       float64     `json:"useCondition"       description:"使用条件 订单金额满这个数才可使用"`
	DiscountPercent    float64     `json:"discountPercent"    description:"折扣比例"`
	UseStartTime       *gtime.Time `json:"useStartTime"       description:"优惠码使用开始时间"`
	UseEndTime         *gtime.Time `json:"useEndTime"         description:"优惠码用结束时间"`
	EventApplyType     int         `json:"eventApplyType"     description:"适用活动方式 1全部活动 2指定活动参与 3指定活动不参与"`
	GoodsApplyType     int         `json:"goodsApplyType"     description:"适用商品方式 1全部商品 2指定商品参与 3指定商品不参与"`
	ProductyId         string      `json:"productyId"         description:"活动 商品ID序列化"`
	FetchLimit         uint        `json:"fetchLimit"         description:"每人领取限额"`
	Status             int         `json:"status"             description:"1-正常，2-删除,3-手动关闭"`
	CreateDate         *gtime.Time `json:"createDate"         description:"新增时间"`
	UpdateDate         *gtime.Time `json:"updateDate"         description:"更新时间"`
	VoucherCodeSubType string      `json:"voucherCodeSubType" description:"区分普通/文惠卡"`
}
