// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeVoucherCodeCreateLog is the golang structure for table evente_voucher_code_create_log.
type EventeVoucherCodeCreateLog struct {
	Id             uint64      `json:"id"             description:""`
	OrgId          int64       `json:"orgId"          description:"主办id"`
	VoucherCodeId  int64       `json:"voucherCodeId"  description:"主办id"`
	Total          int         `json:"total"          description:"总数"`
	Success        int         `json:"success"        description:"成功数量"`
	Fail           int         `json:"fail"           description:"失败数量"`
	ActivationType int         `json:"activationType" description:"生成类型 1:系统生成 2:手动导入 3：手动输入"`
	FailList       string      `json:"failList"       description:""`
	CreateDate     *gtime.Time `json:"createDate"     description:"新增时间"`
	UpdateDate     *gtime.Time `json:"updateDate"     description:"更新时间"`
}
