// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeLimitDiscountOrder is the golang structure for table evente_limit_discount_order.
type EventeLimitDiscountOrder struct {
	Id               int         `json:"id"               description:"自增ID"`
	OrgId            int         `json:"orgId"            description:"主办ID"`
	UserId           int         `json:"userId"           description:"C端用户ID"`
	IncrementId      string      `json:"incrementId"      description:"订单ID"`
	DiscountId       int         `json:"discountId"       description:"限时折扣id"`
	Name             string      `json:"name"             description:"姓名"`
	Code             int         `json:"code"             description:"手机区号"`
	Phone            string      `json:"phone"            description:"手机号"`
	ProductType      string      `json:"productType"      description:"产品类型 （event活动 goods商品)"`
	ProductId        int64       `json:"productId"        description:"产品id"`
	ScreeningsId     int64       `json:"screeningsId"     description:"场次id,只在product_type=event 时有效"`
	OrderMoney       float64     `json:"orderMoney"       description:"下单金额"`
	UseLimitDiscount int         `json:"useLimitDiscount" description:"商品折扣"`
	AmountPayable    float64     `json:"amountPayable"    description:"(适用商品应付金额)"`
	Status           int         `json:"status"           description:"订单状态: 20 已支付 60订单取消"`
	CreateDate       *gtime.Time `json:"createDate"       description:"创建时间"`
	UpdateDate       *gtime.Time `json:"updateDate"       description:"修改时间"`
	BuyNumber        int         `json:"buyNumber"        description:""`
}
