// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeIntegralExchange is the golang structure for table evente_integral_exchange.
type EventeIntegralExchange struct {
	Id            int         `json:"id"            description:"自增id"`
	OrgId         int         `json:"orgId"         description:"主办id"`
	DiscountRatio int         `json:"discountRatio" description:"订单折扣比例（1-99整数）"`
	IntegralRatio int         `json:"integralRatio" description:"积分兑换比例（100积分/1元）"`
	StartDate     *gtime.Time `json:"startDate"     description:"活动开始时间"`
	StopDate      *gtime.Time `json:"stopDate"      description:"活动结束时间"`
	LongTerm      int         `json:"longTerm"      description:"长期有效状态 1有效 2无效"`
	IntegralUsage int64       `json:"integralUsage" description:"积分使用量"`
	Person        int         `json:"person"        description:"人数"`
	PersonNumber  int         `json:"personNumber"  description:"人次"`
	TotalAmount   float64     `json:"totalAmount"   description:"抵现总金额"`
	Status        int         `json:"status"        description:"历史数据，1是 2不是"`
	CreateDate    *gtime.Time `json:"createDate"    description:"创建时间"`
	UpdateDate    *gtime.Time `json:"updateDate"    description:"修改时间"`
}
