// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeReductionProductEvent is the golang structure for table evente_reduction_product_event.
type EventeReductionProductEvent struct {
	Id           int         `json:"id"           description:""`
	OrgId        int         `json:"orgId"        description:"主办ID"`
	ReductionId  int         `json:"reductionId"  description:"满减ID"`
	ProductId    int         `json:"productId"    description:"产品ID"`
	ScreeningsId int         `json:"screeningsId" description:"场次ID"`
	PriceList    string      `json:"priceList"    description:"票品列表集合（逗号分隔）"`
	Status       int         `json:"status"       description:"状态（1.正常 ，2.删除）"`
	CreateDate   *gtime.Time `json:"createDate"   description:"创建时间"`
	UpdateDate   *gtime.Time `json:"updateDate"   description:"更新时间"`
}
