// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeRegimentStock is the golang structure for table evente_regiment_stock.
type EventeRegimentStock struct {
	Id              uint        `json:"id"              description:""`
	OrgId           int         `json:"orgId"           description:"主办id"`
	RegimentId      uint        `json:"regimentId"      description:"团id"`
	ProductId       int         `json:"productId"       description:"产品id"`
	ProductTitle    string      `json:"productTitle"    description:"产品名称"`
	ProductSubId    int         `json:"productSubId"    description:"二级id  例如场次id"`
	ProductSubTitle string      `json:"productSubTitle" description:"二级名称  例如场次名称"`
	ProductRelId    string      `json:"productRelId"    description:"三级id  例如 票品 规格id"`
	ProductRelTitle string      `json:"productRelTitle" description:"三级名称 例如 票品 规格名称"`
	ProductType     string      `json:"productType"     description:"产品类型（event 票务 goods 商品）"`
	Money           float64     `json:"money"           description:"实售价格"`
	ActivityNum     uint        `json:"activityNum"     description:"拼团库存"`
	IsJoin          int         `json:"isJoin"          description:"是否参加 拼团 1 - 参加 0 - 未参加"`
	CreateDate      *gtime.Time `json:"createDate"      description:"创建时间"`
	UpdateDate      *gtime.Time `json:"updateDate"      description:"修改时间"`
}
