// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeMessageOrderTimeout is the golang structure for table evente_message_order_timeout.
type EventeMessageOrderTimeout struct {
	Id               uint        `json:"id"               description:""`
	OrgId            int         `json:"orgId"            description:"org_id"`
	IncrementId      string      `json:"incrementId"      description:"交易ID"`
	Status           uint        `json:"status"           description:"状态 1 未处理 2 已支付 3 已超时 4 已发送"`
	OrderDate        *gtime.Time `json:"orderDate"        description:"下单时间"`
	ExpiredDate      *gtime.Time `json:"expiredDate"      description:"即将超时时间"`
	OrderExpiredDate *gtime.Time `json:"orderExpiredDate" description:"订单超时时间"`
	CreateDate       *gtime.Time `json:"createDate"       description:"新增时间"`
	UpdateDate       *gtime.Time `json:"updateDate"       description:"更新时间"`
	DeleteDate       *gtime.Time `json:"deleteDate"       description:"删除时间"`
}
