// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeOrgWechatAuth is the golang structure for table evente_org_wechat_auth.
type EventeOrgWechatAuth struct {
	Id                     uint        `json:"id"                     description:""`
	OrgId                  int         `json:"orgId"                  description:"org_id"`
	NickName               string      `json:"nickName"               description:"授权方昵称"`
	ServiceTypeInfo        int         `json:"serviceTypeInfo"        description:"类型，0订阅号，1升级后订阅号，2服务号"`
	VerifyTypeInfo         int         `json:"verifyTypeInfo"         description:"认证类型，-1未认证，0微信认证，1新浪微博认证，2腾讯微博认证，3:0+未通过名称认证，4:1+未通过名称认证，5:2+未通过名称认证"`
	UserName               string      `json:"userName"               description:"授权方公众号的原始ID"`
	PrincipalName          string      `json:"principalName"          description:"公众号的主体名称"`
	Alias                  string      `json:"alias"                  description:"公众号的主体名称"`
	HeadImg                string      `json:"headImg"                description:"授权方头像"`
	QrcodeUrl              string      `json:"qrcodeUrl"              description:"二维码"`
	BusinessInfo           string      `json:"businessInfo"           description:"商户功能 序列化"`
	AuthorizerAppid        string      `json:"authorizerAppid"        description:"app_id"`
	AuthorizerRefreshToken string      `json:"authorizerRefreshToken" description:""`
	FuncInfo               string      `json:"funcInfo"               description:"公众号授权给开发者的权限集列表 序列化"`
	AuthorizerInfo         string      `json:"authorizerInfo"         description:"微信返回的序列化"`
	CreateDate             *gtime.Time `json:"createDate"             description:"新增时间"`
	UpdateDate             *gtime.Time `json:"updateDate"             description:"更新时间"`
	DeleteDate             *gtime.Time `json:"deleteDate"             description:"删除时间"`
	Status                 int         `json:"status"                 description:"状态 1:正常 2:取消授权"`
	TemplateList           string      `json:"templateList"           description:""`
}
