// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. 
// =================================================================================

package entity

import(
"github.com/gogf/gf/v2/os/gtime"
)

// EventeLimitDiscountExtend is the golang structure for table evente_limit_discount_extend.
type EventeLimitDiscountExtend struct {
    Id              int         `json:"id"              description:"主键ID"`                           
    OrgId           int         `json:"orgId"           description:"主办ID"`                           
    DiscountId      int         `json:"discountId"      description:"限时折扣ID"`                       
    ProductType     string      `json:"productType"     description:"产品类型 （event活动 goods商品)"`  
    ProductId       uint64      `json:"productId"       description:"产品id"`                           
    ProductName     string      `json:"productName"     description:"产品名称"`                         
    ScreeningsId    int64       `json:"screeningsId"    description:"场次ID"`                           
    ScreeningsName  string      `json:"screeningsName"  description:"场次名称"`                         
    PriceList       string      `json:"priceList"       description:"票品id集合 jason串"`               
    DiscountPercent float64     `json:"discountPercent" description:"折扣比例"`                         
    GoodsPrice      float64     `json:"goodsPrice"      description:"商品价格"`                         
    Status          uint        `json:"status"          description:"状态 1正常 2删除"`                  
    CreateDate      *gtime.Time `json:"createDate"      description:"创建时间"`                         
    UpdateDate      *gtime.Time `json:"updateDate"      description:"修改时间"`                         
}