// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeOrgPushConf is the golang structure for table evente_org_push_conf.
type EventeOrgPushConf struct {
	Id            uint        `json:"id"            description:""`
	OrgId         int         `json:"orgId"         description:"org_id"`
	MessageGroup  string      `json:"messageGroup"  description:"消息分组"`
	MessageType   string      `json:"messageType"   description:"消息推送场景"`
	WeixinPush    int         `json:"weixinPush"    description:"主办公众号开关 1开 0 关"`
	EWeixinPush   int         `json:"eWeixinPush"   description:"活动易公众号开关 1开 0 关"`
	WeixinAppPush int         `json:"weixinAppPush" description:"小程序开关 1开 0 关"`
	SmsPush       int         `json:"smsPush"       description:"开关 1开 0 关"`
	EmailPush     int         `json:"emailPush"     description:"开关 1开 0 关"`
	CreateDate    *gtime.Time `json:"createDate"    description:"新增时间"`
	UpdateDate    *gtime.Time `json:"updateDate"    description:"更新时间"`
	DeleteDate    *gtime.Time `json:"deleteDate"    description:"删除时间"`
}
