// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeVoucherActivation is the golang structure for table evente_voucher_activation.
type EventeVoucherActivation struct {
	Id                uint        `json:"id"                description:"自增id"`
	OrgId             uint        `json:"orgId"             description:"主办id"`
	VoucherCodeId     uint        `json:"voucherCodeId"     description:"优惠码 主表ID"`
	ActivationCode    string      `json:"activationCode"    description:"优惠码 号码"`
	VoucherCodeType   int         `json:"voucherCodeType"   description:"优惠码类型 1:一人一码 2:通用吗"`
	ActivationType    int         `json:"activationType"    description:"生成类型 1:系统生成 2:手动导入 3：手动输入"`
	ActivationDate    *gtime.Time `json:"activationDate"    description:"使用 作废时间"`
	ActivationSubType string      `json:"activationSubType" description:"优惠码类型 nomer 普通  wh_card 文惠卡"`
	Status            int         `json:"status"            description:"使用状态( 1:未使用  2 已使用  3 已作废)"`
	UnlockStatus      int         `json:"unlockStatus"      description:"解锁状态"`
	Remark            string      `json:"remark"            description:"备注"`
	CreateDate        *gtime.Time `json:"createDate"        description:"创建时间"`
	UpdateDate        *gtime.Time `json:"updateDate"        description:""`
	InsertSalt        string      `json:"insertSalt"        description:"插入盐"`
}
