// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeECardActivationExtend is the golang structure for table evente_e_card_activation_extend.
type EventeECardActivationExtend struct {
	Id             uint        `json:"id"             description:"自增id"`
	OrgId          uint        `json:"orgId"          description:"主办id"`
	UserId         uint        `json:"userId"         description:""`
	UserName       string      `json:"userName"       description:"用户名"`
	ActivationId   int         `json:"activationId"   description:"E通卡激活码主表id"`
	ActivationCode string      `json:"activationCode" description:""`
	ActivationDate *gtime.Time `json:"activationDate" description:"激活时间(创建时间)"`
	Status         int         `json:"status"         description:"激活状态( 1: 未激活   2 已激活)"`
	IdCard         string      `json:"idCard"         description:"身份证号"`
	Remark         string      `json:"remark"         description:"备注"`
	AdminName      string      `json:"adminName"      description:"管理员名称"`
	CreateDate     *gtime.Time `json:"createDate"     description:"激活码创建时间"`
	UpdateDate     *gtime.Time `json:"updateDate"     description:""`
	EndDate        *gtime.Time `json:"endDate"        description:"过期时间"`
	SendStatus     int         `json:"sendStatus"     description:"发送状态 1 - 未发送 2 - 已发送"`
	UserMobile     string      `json:"userMobile"     description:"发送手机号"`
}
