// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeCouponExtend is the golang structure for table evente_coupon_extend.
type EventeCouponExtend struct {
	Id            uint64      `json:"id"            description:""`
	OrgId         uint64      `json:"orgId"         description:""`
	CouponId      int64       `json:"couponId"      description:"卡券id"`
	ApplyType     int         `json:"applyType"     description:"适用方式 同主表 2指定参与 3指定不参与"`
	ProductType   string      `json:"productType"   description:"产品类型 （event活动 goods商品 hotel酒店 scenic景点）"`
	ProductId     int64       `json:"productId"     description:"产品id"`
	AllScreenings int         `json:"allScreenings" description:"是否全部场次 0 否 1 是"`
	ScreeningsId  string      `json:"screeningsId"  description:"场次id集合,以,号分割，只在product_type=event&&all_screenings=0 时有效"`
	Status        int         `json:"status"        description:"1-正常，2-删除"`
	CreateDate    *gtime.Time `json:"createDate"    description:"新增时间"`
	UpdateDate    *gtime.Time `json:"updateDate"    description:"更新时间"`
}
