// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeECardSaleGoods is the golang structure for table evente_e_card_sale_goods.
type EventeECardSaleGoods struct {
	Id          int         `json:"id"          description:"自增id"`
	OrgId       uint        `json:"orgId"       description:"主办id"`
	UserId      uint        `json:"userId"      description:"用户id"`
	IncrementId string      `json:"incrementId" description:"订单id"`
	SaleId      int         `json:"saleId"      description:"sale_id"`
	CardId      int         `json:"cardId"      description:"E通卡id"`
	GoodsId     int         `json:"goodsId"     description:"商品id"`
	GiveNumber  int         `json:"giveNumber"  description:"赠送数量"`
	UseNumber   int         `json:"useNumber"   description:"已使用数量"`
	CreateDate  *gtime.Time `json:"createDate"  description:"创建时间"`
	UpdateDate  *gtime.Time `json:"updateDate"  description:"更新时间"`
}
