// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeECardAvoidAppointment is the golang structure for table evente_e_card_avoid_appointment.
type EventeECardAvoidAppointment struct {
	Id                  uint        `json:"id"                  description:"自增id"`
	UserId              uint        `json:"userId"              description:"C端用户id"`
	OrgId               int         `json:"orgId"               description:"主办id"`
	CardId              int         `json:"cardId"              description:"E通卡id"`
	CardSaleId          uint        `json:"cardSaleId"          description:"E通卡销售表id"`
	PicId               uint        `json:"picId"               description:"活动图片id"`
	EventeId            int         `json:"eventeId"            description:"活动id"`
	EventeName          string      `json:"eventeName"          description:"活动名称"`
	ScreeningsId        int         `json:"screeningsId"        description:"场次id"`
	ScreeningsName      string      `json:"screeningsName"      description:"场次名称"`
	ScreeningsStartDate *gtime.Time `json:"screeningsStartDate" description:"场次开始时间"`
	ScreeningsEndDate   *gtime.Time `json:"screeningsEndDate"   description:"场次结束时间"`
	VerificationName    string      `json:"verificationName"    description:"核销人-主办名称"`
	CreateDate          *gtime.Time `json:"createDate"          description:"创建时间"`
	UpdateDate          *gtime.Time `json:"updateDate"          description:"修改时间"`
}
