// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeLimitDiscountLog is the golang structure for table evente_limit_discount_log.
type EventeLimitDiscountLog struct {
	Id             int         `json:"id"             description:"主键ID"`
	OrgId          int         `json:"orgId"          description:"主办ID"`
	BeforeJsonData string      `json:"beforeJsonData" description:"修改之前操作记录数据"`
	AfterJsonData  string      `json:"afterJsonData"  description:"修改之后操作记录数据"`
	CreateDate     *gtime.Time `json:"createDate"     description:"创建时间"`
}
