// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeOpenRegiment is the golang structure for table evente_open_regiment.
type EventeOpenRegiment struct {
	Id                  uint        `json:"id"                  description:""`
	OrgId               int         `json:"orgId"               description:"主办id"`
	RegimentId          uint        `json:"regimentId"          description:"团id"`
	UserId              uint        `json:"userId"              description:"用户id"`
	ProductType         string      `json:"productType"         description:"产品类型（event 票务 goods 商品）"`
	ProductId           int         `json:"productId"           description:"产品id"`
	GroupIncrementId    string      `json:"groupIncrementId"    description:"团订单号"`
	SuccessStatus       int         `json:"successStatus"       description:"是否成团 0 - 未成团 1 - 已成团"`
	RegimentStatus      int         `json:"regimentStatus"      description:"拼团状态 0 - 拼团中 1 - 拼团成功 2 - 拼团失败"`
	OfferedNumber       int         `json:"offeredNumber"       description:"参团人数"`
	SuccessRegimentType int         `json:"successRegimentType" description:"1 - 普通成团 2- 模拟成团"`
	RegimentNote        string      `json:"regimentNote"        description:"成功(失败)备注"`
	SuccessRegimentDate *gtime.Time `json:"successRegimentDate" description:""`
	CreateDate          *gtime.Time `json:"createDate"          description:"创建时间"`
	UpdateDate          *gtime.Time `json:"updateDate"          description:"修改时间"`
	ExpiryDate          *gtime.Time `json:"expiryDate"          description:""`
	Pending             int         `json:"pending"             description:""`
}
