// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeCouponNumber is the golang structure for table evente_coupon_number.
type EventeCouponNumber struct {
	Id             uint64      `json:"id"             description:""`
	OrgId          int64       `json:"orgId"          description:"主办id"`
	UserId         int64       `json:"userId"         description:"用户id"`
	CouponId       int64       `json:"couponId"       description:"卡券id"`
	Status         int         `json:"status"         description:"1正常，2已删除，3已使用"`
	UseIncrementId string      `json:"useIncrementId" description:"使用订单"`
	UseDate        int         `json:"useDate"        description:"使用时间"`
	CouponSource   string      `json:"couponSource"   description:"优惠券来源  normal  普通领取  integral  积分赠送"`
	CreateDate     *gtime.Time `json:"createDate"     description:"新增时间"`
	UpdateDate     *gtime.Time `json:"updateDate"     description:"更新时间"`
}
