// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeRegimentOrder is the golang structure for table evente_regiment_order.
type EventeRegimentOrder struct {
	Id               int         `json:"id"               description:"自增id"`
	OrgId            uint        `json:"orgId"            description:"主办id"`
	UserId           uint        `json:"userId"           description:"用户id"`
	GroupIncrementId string      `json:"groupIncrementId" description:"团订单id"`
	IncrementId      string      `json:"incrementId"      description:"主订单id"`
	RegimentId       int         `json:"regimentId"       description:"团id"`
	OpenRegimentId   int         `json:"openRegimentId"   description:"开团id"`
	Name             string      `json:"name"             description:"购买人名称"`
	Mobile           string      `json:"mobile"           description:"手机号"`
	CountryCode      string      `json:"countryCode"      description:"国别"`
	OrderMoney       float64     `json:"orderMoney"       description:"订单总金额"`
	OrderNumber      uint        `json:"orderNumber"      description:"购买数量"`
	OrderState       uint        `json:"orderState"       description:"订单状态 10 待支付 20 已支付 30 已发货 40 已完成 50 订单超时 60 订单取消"`
	RefundState      uint        `json:"refundState"      description:"0无退款、1 处理中、2退款失败、3 已退款"`
	OrderType        string      `json:"orderType"        description:"订单类型(event,goods)"`
	ProductId        int         `json:"productId"        description:"产品id"`
	ProductTitle     string      `json:"productTitle"     description:"产品名称"`
	PayWay           string      `json:"payWay"           description:"支付方式(alipay 支付宝 weixin 微信  free免费订单)"`
	PayDate          *gtime.Time `json:"payDate"          description:"支付时间"`
	CreateDate       *gtime.Time `json:"createDate"       description:"创建时间"`
	UpdateDate       *gtime.Time `json:"updateDate"       description:"更新时间"`
	JoinType         int         `json:"joinType"         description:""`
}
