// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeECard is the golang structure for table evente_e_card.
type EventeECard struct {
	Id                 uint        `json:"id"                 description:""`
	OrgId              int         `json:"orgId"              description:"主办id"`
	CardName           string      `json:"cardName"           description:"E通卡名称"`
	SaleStartDate      *gtime.Time `json:"saleStartDate"      description:"售卖开始时间"`
	SaleStopDate       *gtime.Time `json:"saleStopDate"       description:"售卖结束时间"`
	Colour             string      `json:"colour"             description:"年卡背景颜色"`
	ImgId              int         `json:"imgId"              description:"年卡图片id"`
	IssueNum           int         `json:"issueNum"           description:"发行量"`
	Price              float64     `json:"price"              description:"价格"`
	ValidStatus        int         `json:"validStatus"        description:"有效期状态（1.购买日自然年有效 2.购买日多少天有效 3.自定义）"`
	ValidUntil         string      `json:"validUntil"         description:"开始结束时间用，分割/多少天有效"`
	Usage              int         `json:"usage"              description:"使用方式 1、预约 2、免预约"`
	BeforehandNum      uint        `json:"beforehandNum"      description:"总预约次数"`
	UserInformation    string      `json:"userInformation"    description:"1、姓名 2、手机号 3、身份证 4、一寸照 多个，分割"`
	CardExplain        string      `json:"cardExplain"        description:"E通卡说明"`
	BuyNum             uint        `json:"buyNum"             description:"直接购买量"`
	ActivationCodeNum  uint        `json:"activationCodeNum"  description:"激活码生成总量"`
	ActivationUsageNum uint        `json:"activationUsageNum" description:"激活码使用量（激活量）"`
	Stock              uint        `json:"stock"              description:"库存"`
	SaleStatus         int         `json:"saleStatus"         description:"售卖状态 1、开启售卖 2、关闭售卖"`
	CreateDate         *gtime.Time `json:"createDate"         description:"创建时间"`
	UpdateDate         *gtime.Time `json:"updateDate"         description:"修改时间"`
	CheckNum           int         `json:"checkNum"           description:"每天可核销数量"`
	TextColour         string      `json:"textColour"         description:"年卡文字颜色"`
	Cancellation       int         `json:"cancellation"       description:"是否可取消预约"`
	CancellationTime   string      `json:"cancellationTime"   description:"年卡可取消时间序列化"`
	GiveMember         int         `json:"giveMember"         description:"赠送会员等级"`
	DeliveryAddress    string      `json:"deliveryAddress"    description:"商品取货地址"`
	ContainGoods       int         `json:"containGoods"       description:"是否包含商品"`
}
