// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeFreeShipping is the golang structure for table evente_free_shipping.
type EventeFreeShipping struct {
	Id               int         `json:"id"               description:""`
	OrgId            int         `json:"orgId"            description:"主办ID"`
	Title            string      `json:"title"            description:"商品标题"`
	FreeShippingMode int         `json:"freeShippingMode" description:"包邮方式(1.满额包邮  2.满件包邮)"`
	FreeShippingType int         `json:"freeShippingType" description:"包邮条件（1.按商品优惠前总价，计算包邮  2.按商品优惠后总价，计算包邮）"`
	StartDate        *gtime.Time `json:"startDate"        description:"开始时间"`
	EndDate          *gtime.Time `json:"endDate"          description:"结束时间"`
	Rule             string      `json:"rule"             description:"包邮地区规则"`
	CoverImg         int         `json:"coverImg"         description:"封面图ID"`
	ProductType      string      `json:"productType"      description:"产品类型（event 演出活动,goods 商品类型）"`
	IsCurrency       int         `json:"isCurrency"       description:"是否夸商品优惠（1是 2.否）"`
	ProductList      string      `json:"productList"      description:"产品ID集合"`
	Status           int         `json:"status"           description:"商品状态（1正常 2删除）"`
	CreateDate       *gtime.Time `json:"createDate"       description:"创建时间"`
	UpdateDate       *gtime.Time `json:"updateDate"       description:"更新时间"`
}
